// Mocks generated by Mockito 5.4.4 from annotations
// in aranduapp/test/ui/journey/view/journey_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:aranduapp/core/state/command.dart' as _i2;
import 'package:aranduapp/ui/journey/model/journey_model.dart' as _i5;
import 'package:aranduapp/ui/journey/viewmodel/journey_viewmodel.dart' as _i4;
import 'package:async/async.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCommand1_0<T, A> extends _i1.SmartFake
    implements _i2.Command1<T, A> {
  _FakeCommand1_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResult_1<T> extends _i1.SmartFake implements _i3.Result<T> {
  _FakeResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [JourneyViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockJourneyViewModel extends _i1.Mock implements _i4.JourneyViewModel {
  @override
  _i2.Command1<List<_i5.JourneyModel>, String> get getJourneyCommand =>
      (super.noSuchMethod(
        Invocation.getter(#getJourneyCommand),
        returnValue: _FakeCommand1_0<List<_i5.JourneyModel>, String>(
          this,
          Invocation.getter(#getJourneyCommand),
        ),
        returnValueForMissingStub:
            _FakeCommand1_0<List<_i5.JourneyModel>, String>(
          this,
          Invocation.getter(#getJourneyCommand),
        ),
      ) as _i2.Command1<List<_i5.JourneyModel>, String>);

  @override
  set getJourneyCommand(
          _i2.Command1<List<_i5.JourneyModel>, String>? _getJourneyCommand) =>
      super.noSuchMethod(
        Invocation.setter(
          #getJourneyCommand,
          _getJourneyCommand,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isReloadingData => (super.noSuchMethod(
        Invocation.getter(#isReloadingData),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<_i3.Result<List<_i5.JourneyModel>>> getJourney(
          String? subjectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJourney,
          [subjectId],
        ),
        returnValue: _i6.Future<_i3.Result<List<_i5.JourneyModel>>>.value(
            _FakeResult_1<List<_i5.JourneyModel>>(
          this,
          Invocation.method(
            #getJourney,
            [subjectId],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.Result<List<_i5.JourneyModel>>>.value(
                _FakeResult_1<List<_i5.JourneyModel>>(
          this,
          Invocation.method(
            #getJourney,
            [subjectId],
          ),
        )),
      ) as _i6.Future<_i3.Result<List<_i5.JourneyModel>>>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Command1].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommand1<T, A> extends _i1.Mock implements _i2.Command1<T, A> {
  @override
  _i6.Future<_i3.Result<T>> Function(A) get action => (super.noSuchMethod(
        Invocation.getter(#action),
        returnValue: (A __p0) =>
            _i6.Future<_i3.Result<T>>.value(_FakeResult_1<T>(
          this,
          Invocation.getter(#action),
        )),
        returnValueForMissingStub: (A __p0) =>
            _i6.Future<_i3.Result<T>>.value(_FakeResult_1<T>(
          this,
          Invocation.getter(#action),
        )),
      ) as _i6.Future<_i3.Result<T>> Function(A));

  @override
  bool get isError => (super.noSuchMethod(
        Invocation.getter(#isError),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isOk => (super.noSuchMethod(
        Invocation.getter(#isOk),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get running => (super.noSuchMethod(
        Invocation.getter(#running),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<_i3.Result<T>> execute(A? arg1) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [arg1],
        ),
        returnValue: _i6.Future<_i3.Result<T>>.value(_FakeResult_1<T>(
          this,
          Invocation.method(
            #execute,
            [arg1],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.Result<T>>.value(_FakeResult_1<T>(
          this,
          Invocation.method(
            #execute,
            [arg1],
          ),
        )),
      ) as _i6.Future<_i3.Result<T>>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
