// Mocks generated by Mockito 5.4.4 from annotations
// in aranduapp/test/ui/edit_profile/view/edit_profile_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:aranduapp/core/network/token_manager/model/user_model.dart'
    as _i6;
import 'package:aranduapp/core/state/command.dart' as _i2;
import 'package:aranduapp/ui/edit_profile/model/edit_profile_request.dart'
    as _i5;
import 'package:aranduapp/ui/edit_profile/viewmodel/edit_profile_viewmodel.dart'
    as _i4;
import 'package:async/async.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCommand1_0<T, A> extends _i1.SmartFake
    implements _i2.Command1<T, A> {
  _FakeCommand1_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommand0_1<T> extends _i1.SmartFake implements _i2.Command0<T> {
  _FakeCommand0_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResult_2<T> extends _i1.SmartFake implements _i3.Result<T> {
  _FakeResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EditProfileViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileViewModel extends _i1.Mock
    implements _i4.EditProfileViewModel {
  @override
  _i2.Command1<void, _i5.EditProfileRequest> get editCommand =>
      (super.noSuchMethod(
        Invocation.getter(#editCommand),
        returnValue: _FakeCommand1_0<void, _i5.EditProfileRequest>(
          this,
          Invocation.getter(#editCommand),
        ),
        returnValueForMissingStub:
            _FakeCommand1_0<void, _i5.EditProfileRequest>(
          this,
          Invocation.getter(#editCommand),
        ),
      ) as _i2.Command1<void, _i5.EditProfileRequest>);

  @override
  set editCommand(_i2.Command1<void, _i5.EditProfileRequest>? _editCommand) =>
      super.noSuchMethod(
        Invocation.setter(
          #editCommand,
          _editCommand,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Command0<void> get getUserCommand => (super.noSuchMethod(
        Invocation.getter(#getUserCommand),
        returnValue: _FakeCommand0_1<void>(
          this,
          Invocation.getter(#getUserCommand),
        ),
        returnValueForMissingStub: _FakeCommand0_1<void>(
          this,
          Invocation.getter(#getUserCommand),
        ),
      ) as _i2.Command0<void>);

  @override
  set getUserCommand(_i2.Command0<void>? _getUserCommand) => super.noSuchMethod(
        Invocation.setter(
          #getUserCommand,
          _getUserCommand,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set user(_i6.UserModel? _user) => super.noSuchMethod(
        Invocation.setter(
          #user,
          _user,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Future<_i3.Result<void>> editProfile(_i5.EditProfileRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [request],
        ),
        returnValue: _i7.Future<_i3.Result<void>>.value(_FakeResult_2<void>(
          this,
          Invocation.method(
            #editProfile,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i3.Result<void>>.value(_FakeResult_2<void>(
          this,
          Invocation.method(
            #editProfile,
            [request],
          ),
        )),
      ) as _i7.Future<_i3.Result<void>>);

  @override
  _i7.Future<_i3.Result<_i6.UserModel>> getUser() => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [],
        ),
        returnValue: _i7.Future<_i3.Result<_i6.UserModel>>.value(
            _FakeResult_2<_i6.UserModel>(
          this,
          Invocation.method(
            #getUser,
            [],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i3.Result<_i6.UserModel>>.value(
            _FakeResult_2<_i6.UserModel>(
          this,
          Invocation.method(
            #getUser,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Result<_i6.UserModel>>);

  @override
  void addListener(dynamic listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(dynamic listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Command1].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommand1<T, A> extends _i1.Mock implements _i2.Command1<T, A> {
  @override
  _i7.Future<_i3.Result<T>> Function(A) get action => (super.noSuchMethod(
        Invocation.getter(#action),
        returnValue: (A __p0) =>
            _i7.Future<_i3.Result<T>>.value(_FakeResult_2<T>(
          this,
          Invocation.getter(#action),
        )),
        returnValueForMissingStub: (A __p0) =>
            _i7.Future<_i3.Result<T>>.value(_FakeResult_2<T>(
          this,
          Invocation.getter(#action),
        )),
      ) as _i7.Future<_i3.Result<T>> Function(A));

  @override
  bool get isError => (super.noSuchMethod(
        Invocation.getter(#isError),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isOk => (super.noSuchMethod(
        Invocation.getter(#isOk),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get running => (super.noSuchMethod(
        Invocation.getter(#running),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Future<_i3.Result<T>> execute(A? arg1) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [arg1],
        ),
        returnValue: _i7.Future<_i3.Result<T>>.value(_FakeResult_2<T>(
          this,
          Invocation.method(
            #execute,
            [arg1],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i3.Result<T>>.value(_FakeResult_2<T>(
          this,
          Invocation.method(
            #execute,
            [arg1],
          ),
        )),
      ) as _i7.Future<_i3.Result<T>>);

  @override
  void addListener(dynamic listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(dynamic listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
