// Mocks generated by Mockito 5.4.4 from annotations
// in aranduapp/test/ui/register_account/view/register_account_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i6;

import 'package:aranduapp/core/state/command.dart' as _i2;
import 'package:aranduapp/ui/register_account/model/register_request.dart'
    as _i5;
import 'package:aranduapp/ui/register_account/viewmodel/register_viewmodel.dart'
    as _i4;
import 'package:async/async.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCommand1_0<T, A> extends _i1.SmartFake
    implements _i2.Command1<T, A> {
  _FakeCommand1_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResult_1<T1> extends _i1.SmartFake implements _i3.Result<T1> {
  _FakeResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RegisterAccountViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterAccountViewModel extends _i1.Mock
    implements _i4.RegisterAccountViewModel {
  @override
  bool get isTermsAccepted => (super.noSuchMethod(
        Invocation.getter(#isTermsAccepted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isTermsAccepted(bool? _isTermsAccepted) => super.noSuchMethod(
        Invocation.setter(
          #isTermsAccepted,
          _isTermsAccepted,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Command1<void, _i5.RegisterRequest> get registerCommand =>
      (super.noSuchMethod(
        Invocation.getter(#registerCommand),
        returnValue: _FakeCommand1_0<void, _i5.RegisterRequest>(
          this,
          Invocation.getter(#registerCommand),
        ),
        returnValueForMissingStub: _FakeCommand1_0<void, _i5.RegisterRequest>(
          this,
          Invocation.getter(#registerCommand),
        ),
      ) as _i2.Command1<void, _i5.RegisterRequest>);

  @override
  set registerCommand(
          _i2.Command1<void, _i5.RegisterRequest>? _registerCommand) =>
      super.noSuchMethod(
        Invocation.setter(
          #registerCommand,
          _registerCommand,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setToggleTermsAccepted(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setToggleTermsAccepted,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Command1].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommand1<T, A> extends _i1.Mock implements _i2.Command1<T, A> {
  @override
  _i7.Future<_i3.Result<T>> Function(A) get action => (super.noSuchMethod(
        Invocation.getter(#action),
        returnValue: (A __p0) =>
            _i7.Future<_i3.Result<T>>.value(_FakeResult_1<T>(
          this,
          Invocation.getter(#action),
        )),
        returnValueForMissingStub: (A __p0) =>
            _i7.Future<_i3.Result<T>>.value(_FakeResult_1<T>(
          this,
          Invocation.getter(#action),
        )),
      ) as _i7.Future<_i3.Result<T>> Function(A));

  @override
  bool get isError => (super.noSuchMethod(
        Invocation.getter(#isError),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isOk => (super.noSuchMethod(
        Invocation.getter(#isOk),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get running => (super.noSuchMethod(
        Invocation.getter(#running),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Future<_i3.Result<T>> execute(A? arg1) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [arg1],
        ),
        returnValue: _i7.Future<_i3.Result<T>>.value(_FakeResult_1<T>(
          this,
          Invocation.method(
            #execute,
            [arg1],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i3.Result<T>>.value(_FakeResult_1<T>(
          this,
          Invocation.method(
            #execute,
            [arg1],
          ),
        )),
      ) as _i7.Future<_i3.Result<T>>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
